"""empty message

Revision ID: 6998bed2a4fe
Revises: 
Create Date: 2025-09-18 21:37:13.010437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6998bed2a4fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('order')

    # ### end Alembic commands ###
